import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-prime-brokerage-margin-interest-audit",
  "engine": "recovery",
  "title": "Prime Brokerage Margin Interest Audit",
  "shortTitle": "Prime Brokerage Margin Interest Audit",
  "tagline": "Audit debit interest, credit interest, financing spreads, and balance netting across prime-broker accounts.",
  "industry": "Capital Markets Cost Assurance",
  "buyer": "Hedge funds and institutional investors",
  "uiPort": 4671,
  "apiPort": 5671,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Prime Brokerage Margin Interest Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash in one accountable workflow. Audit debit interest, credit interest, financing spreads, and balance netting across prime-broker accounts.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Prime Brokerage Margin Interest Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("prime-agreement-library","PBM01","Prime agreement library","Execute prime agreement library using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed prime agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Prime agreement library Reference","text","PBM01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("account-entity-hierarchy","PBM02","Account entity hierarchy","Execute account entity hierarchy using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed account entity hierarchy decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Account entity hierarchy Reference","text","PBM02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("daily-cash-balance-ingestion","PBM03","Daily cash balance ingestion","Execute daily cash balance ingestion using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed daily cash balance ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Daily cash balance ingestion Reference","text","PBM03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("margin-loan-calculation","PBM04","Margin loan calculation","Execute margin loan calculation using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed margin loan calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Margin loan calculation Reference","text","PBM04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("benchmark-rate-validation","PBM05","Benchmark rate validation","Execute benchmark rate validation using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed benchmark rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Benchmark rate validation Reference","text","PBM05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("spread-tier-calculation","PBM06","Spread tier calculation","Execute spread tier calculation using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed spread tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Spread tier calculation Reference","text","PBM06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("day-count-convention","PBM07","Day-count convention","Execute day-count convention using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed day-count convention decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Day-count convention Reference","text","PBM07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("currency-basis-adjustment","PBM08","Currency basis adjustment","Execute currency basis adjustment using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed currency basis adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Currency basis adjustment Reference","text","PBM08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("cross-account-netting","PBM09","Cross-account netting","Execute cross-account netting using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed cross-account netting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Cross-account netting Reference","text","PBM09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("credit-interest-calculation","PBM10","Credit interest calculation","Execute credit interest calculation using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed credit interest calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Credit interest calculation Reference","text","PBM10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("stock-borrow-fee-linkage","PBM11","Stock borrow fee linkage","Execute stock borrow fee linkage using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed stock borrow fee linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Stock borrow fee linkage Reference","text","PBM11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("statement-charge-matching","PBM12","Statement charge matching","Execute statement charge matching using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed statement charge matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Statement charge matching Reference","text","PBM12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("broker-dispute-workflow","PBM13","Broker dispute workflow","Execute broker dispute workflow using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed broker dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Broker dispute workflow Reference","text","PBM13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("cash-credit-reconciliation","PBM14","Cash credit reconciliation","Execute cash credit reconciliation using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed cash credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Cash credit reconciliation Reference","text","PBM14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]}),
feature("broker-fund-analytics","PBM15","Broker fund analytics","Execute broker fund analytics using prime brokerage agreements, cash balances, margin loans, securities positions, benchmark rates, spreads, day counts, stock borrow, fees, statements, and cash.","Produce a governed broker fund analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Prime Broker / Fund Account","text","Prime Broker / Fund Account · Standard Case"],["caseReference","Broker fund analytics Reference","text","PBM15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",892500],["supportedAmount","Evidence-Supported Amount","currency",749700],["domainDriver","Balance Type","select","Debit cash",["Debit cash","Credit cash","Margin loan"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Prime agreement library case","Account entity hierarchy case","Daily cash balance ingestion case","Margin loan calculation case","Benchmark rate validation case"]})
]);
